### ISSUE TITLE
Move package to the mapbox namespace.

### ISSUE THREAD

**Issue by arunasank** [mapbox/decrypt-kms-env#7]

**Comment by k-mahoney** [comment]
Update here, package is still not under `@mapbox` namespace and the only listed collaborator is @yhahn. Is there anything barring this from migration @mapbox/security? I know we have some outlier cases due to issues with NPM that cannot be added to Mapbox with ease.

https://www.npmjs.com/package/decrypt-kms-env

**Comment by zmully** [comment]
No problems moving into the @mapbox namespace @k-mahoney.

**Comment by k-mahoney** [comment]
Thanks @zmully 👍
